name: demo-ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-or-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Bootstrap core
        shell: bash
        run: |
          set -e
          bash bootstrap/fetch-core-demo.sh main
          echo "Core tree (depth 3):"
          find .work/core -maxdepth 3 -type d | sed 's#^#  #'

      - name: Install core dependencies
        shell: bash
        env:
          ELECTRON_SKIP_BINARY_DOWNLOAD: "1"
        run: |
          pnpm -C .work/core install || true

      - name: Try to build a Vite UI if present
        id: build
        shell: bash
        run: |
          set -e
          mkdir -p dist
          VITE_DIR="$(find .work/core -type f -name 'vite.config.*' -printf '%h\n' | head -n1 || true)"
          if [ -n "$VITE_DIR" ] && [ -d "$VITE_DIR" ]; then
            echo "Building Vite project at $VITE_DIR"
            pnpm -C "$VITE_DIR" install || true
            pnpm -C "$VITE_DIR" build || pnpm -C "$VITE_DIR" vite build
            FOUND_DIST="$(find "$VITE_DIR" -type d -name dist -maxdepth 4 | head -n1 || true)"
            if [ -n "$FOUND_DIST" ]; then
              cp -r "$FOUND_DIST"/* dist/
              echo "mode=pwa" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          fi
          echo "No Vite UI found. Will package demo installers."
          echo "mode=bundle" >> "$GITHUB_OUTPUT"

      - name: Package demo installers (bundle)
        if: steps.build.outputs.mode == 'bundle'
        shell: bash
        run: |
          set -e
          mkdir -p artifacts
          BUNDLE="$(find .work/core -maxdepth 1 -type d -iname 'anarqq-ecosystem-demo-*' | head -n1 || true)"
          if [ -n "$BUNDLE" ]; then
            (cd "$BUNDLE" && zip -r "$GITHUB_WORKSPACE/artifacts/anarqq-ecosystem-demo.zip" .)
          else
            # fallback: si ya existe el zip en raíz del core, cópialo
            EXISTING="$(ls .work/core/anarqq-ecosystem-demo-installers-*.zip 2>/dev/null | head -n1 || true)"
            if [ -n "$EXISTING" ]; then
              mkdir -p artifacts
              cp "$EXISTING" artifacts/anarqq-ecosystem-demo.zip
            else
              echo "No demo bundle found."; exit 1
            fi
          fi

      - name: Upload PWA artifact
        if: steps.build.outputs.mode == 'pwa'
        uses: actions/upload-artifact@v4
        with:
          name: qsocial-pwa
          path: dist

      - name: Upload demo bundle
        if: steps.build.outputs.mode == 'bundle'
        uses: actions/upload-artifact@v4
        with:
          name: anarqq-ecosystem-demo
          path: artifacts/anarqq-ecosystem-demo.zip

