name: demo-ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-pwa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Bootstrap core
        shell: bash
        run: |
          bash bootstrap/fetch-core-demo.sh main
          echo "Contents of .work/core (depth 2):"
          find .work/core -maxdepth 2 -type d

      - name: Install core dependencies
        shell: bash
        env:
          ELECTRON_SKIP_BINARY_DOWNLOAD: "1"
        run: |
          pnpm -C .work/core install

      - name: Locate Qsocial package
        id: locate
        shell: bash
        run: |
          set -e
          echo "Scanning for qsocial package.json under .work/core ..."
          QSOCIAL_DIR=""
          while IFS= read -r f; do
            if grep -qi '"name"[^"]*qsocial' "$f"; then
              QSOCIAL_DIR="$(dirname "$f")"
              break
            fi
          done < <(find .work/core -type f -name package.json)

          if [ -z "$QSOCIAL_DIR" ] || [ ! -d "$QSOCIAL_DIR" ]; then
            echo "Could not locate Qsocial by scanning package.json files."
            echo "Dumping top-level structure for debugging:"
            find .work/core -maxdepth 3 -type d | sed 's#^#  #g' | head -n 200
          else
            echo "QSOCIAL_DIR=$QSOCIAL_DIR" | tee -a "$GITHUB_ENV"
          fi

      - name: Build Qsocial (PWA)
        shell: bash
        run: |
          set -e
          if [ -n "${QSOCIAL_DIR:-}" ] && [ -d "$QSOCIAL_DIR" ]; then
            echo "Building at $QSOCIAL_DIR"
            pnpm -C "$QSOCIAL_DIR" build || pnpm -C "$QSOCIAL_DIR" vite build
            mkdir -p dist
            cp -r "$QSOCIAL_DIR"/dist/* dist/
          else
            echo "Fallback: using pnpm filter '*qsocial*' from core root"
            pnpm -C .work/core -r --filter "*qsocial*" build
            FOUND_DIST="$(find .work/core -type d -path "*/dist" -maxdepth 6 | head -n1 || true)"
            if [ -z "$FOUND_DIST" ]; then
              echo "No dist found after fallback build"
              exit 1
            fi
            echo "Using dist at $FOUND_DIST"
            mkdir -p dist
            cp -r "$FOUND_DIST"/* dist/
          fi

      - name: Upload PWA artifact (zip)
        shell: bash
        run: |
          mkdir -p artifacts
          (cd dist && zip -r ../artifacts/qsocial-pwa.zip .)

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: qsocial-pwa
          path: artifacts/qsocial-pwa.zip

